### ISSUE TITLE
App crashes on application startup after setup

### ISSUE THREAD

**Issue by Shkzeen** [seemoo-lab/AirGuard#148]
I managed to replicate the crash by giving location permission (precise) and starting search. Still broken even after #133
StackTrace:
```
FATAL EXCEPTION: main
Process: de.seemoo.at_tracking_detection, PID: 6741
java.lang.RuntimeException: Unable to resume activity {de.seemoo.at_tracking_detection/de.seemoo.at_tracking_detection.ui.MainActivity}: java.lang.IllegalArgumentException: provider "network" does not exist
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4824)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4857)
	at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:54)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.IllegalArgumentException: provider "network" does not exist
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2430)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.os.Parcel.readException(Parcel.java:2335)
	at android.location.ILocationManager$Stub$Proxy.registerLocationListener(ILocationManager.java:1445)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1498)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1186)
	at android.location.LocationManager.requestLocationUpdates(LocationManager.java:1151)
	at de.seemoo.at_tracking_detection.detection.LocationProvider.requestLegacyLocationUpdatesFromAnyProvider(Unknown Source:71)
	at de.seemoo.at_tracking_detection.detection.LocationProvider.lastKnownOrRequestLocationUpdates(Unknown Source:41)
	at de.seemoo.at_tracking_detection.util.ble.BLEScanner.fetchCurrentLocation(Unknown Source:19)
	at de.seemoo.at_tracking_detection.util.ble.BLEScanner.startBluetoothScan(Unknown Source:99)
	at de.seemoo.at_tracking_detection.ui.MainActivity.onResume(Unknown Source:24)
	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1488)
	at android.app.Activity.performResume(Activity.java:8197)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4814)
	... 13 more
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.internal.util.Preconditions.checkArgument(Preconditions.java:59)
	at com.android.server.location.LocationManagerService.registerLocationListener(LocationManagerService.java:720)
	at android.location.ILocationManager$Stub.onTransact(ILocationManager.java:585)
	at android.os.Binder.execTransactInternal(Binder.java:1184)
	at android.os.Binder.execTransact(Binder.java:1143)
```

**Comment by Sn0wfreezeDev** [comment]
That should be fixed on our dev branch 😊
